site_name: LangGraph4j
docs_dir: target/mkdocs
site_dir: target/sitedocs
repo_url: https://github.com/bsorrentino/langgraph4j
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: images/langgraph4j-icon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - toc.integrate.toc
    - toc.integrate.toc.inline
    - search.suggest
    - search.highlight
extra:
  version:
    provider: mike
plugins:
  - mkdocs-jupyter
  - search
  - tags
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
nav:
  - Home: 
    - Overview: index.md    
    # - Core Library:       
    #   - Examples: https://github.com/langgraph4j/langgraph4j-examples
    #   - JavaDoc: apidocs/index.html
    - Getting Started: getting-started.md
    - How to(s):
      - Add persistence (“memory”) to your graph: how-tos/persistence.ipynb
      - Adaptive RAG: how-tos/adaptiverag.ipynb
      - Agent Executor: how-tos/agentexecutor.ipynb
      - Agent Executor with MCP: how-tos/agentexecutor-mcp.ipynb
      - Agentic RAG: how-tos/agentic-rag.ipynb
      - Basic Reflection: how-tos/basic-reflection.ipynb
      - Corrective RAG: how-tos/corrective-rag.ipynb
      - Hooks: how-tos/hooks.ipynb
      - Langchain4j LLM Streaming: how-tos/llm-streaming.ipynb
      - Multi-agent supervisor: how-tos/multi-agent-supervisor.ipynb
      - Parallel Branch: how-tos/parallel-branch.ipynb
      - PlantUML: how-tos/plantuml.ipynb
      - Plan-and-Execute: how-tos/plan-and-execute.ipynb
      - Prompt Chaining: how-tos/prompt-chaining.ipynb
      - Subgraph as compiled graph: how-tos/subgraph-as-compiledgraph.ipynb
      - Subgraph as node action: how-tos/subgraph-as-nodeaction.ipynb
      - Subgraph as state graph: how-tos/subgraph-as-stategraph.ipynb
      - View and Update past graph state: how-tos/time-travel.ipynb
      - Wait for User input: how-tos/wait-user-input.ipynb
    - Integrations: 
      - integrations/spring-ai/README.md
      - integrations/langchain4j/README.md
    - Studio: studio/index.md
    - Builder: builder/index.md
    - Latest Release Notes: https://github.com/langgraph4j/langgraph4j/releases
  - Tutorial:
      - Core Library: core/core-library.md
      - Hooks: core/hooks.md      
      - Parallel Branch: core/parallel-branch.md
      - Streaming: core/streaming.md
      - Subgraphs: core/subgraph.md
      - Cancellation: core/cancellation.md
      - Checkpoint (Postgres): core/checkpoint-postgres.md
  - Features: features.md  
  - Examples: https://github.com/langgraph4j/langgraph4j-examples
  - How to(s): 
      - Add persistence (“memory”) to your graph: how-tos/persistence.ipynb
      - Adaptive RAG: how-tos/adaptiverag.ipynb
      - Agent Executor: how-tos/agentexecutor.ipynb
      - Agent Executor with MCP: how-tos/agentexecutor-mcp.ipynb
      - Basic Reflection: how-tos/basic-reflection.ipynb
      - Corrective RAG: how-tos/corrective-rag.ipynb
      - Hooks: how-tos/hooks.ipynb
      - Langchain4j LLM Streaming: how-tos/llm-streaming.ipynb
      - Multi-agent supervisor: how-tos/multi-agent-supervisor.ipynb
      - Parallel Branch: how-tos/parallel-branch.ipynb
      - PlantUML: how-tos/plantuml.ipynb
      - Plan-and-Execute: how-tos/plan-and-execute.ipynb
      - Subgraph as compiled graph: how-tos/subgraph-as-compiledgraph.ipynb
      - Subgraph as node action: how-tos/subgraph-as-nodeaction.ipynb
      - Subgraph as state graph: how-tos/subgraph-as-stategraph.ipynb
      - View and Update past graph state: how-tos/time-travel.ipynb
      - Wait for User input: how-tos/wait-user-input.ipynb
  - References: references.md
  - JavaDoc: apidocs/index.html
