-- sqlCreateTables
CREATE TABLE IF NOT EXISTS LANGRAPH4J_THREAD (
   thread_id VARCHAR2(36) PRIMARY KEY,
   thread_name VARCHAR(255),
   is_released BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_LANGRAPH4J_THREAD_NAME_RELEASED
  ON LANGRAPH4J_THREAD(thread_name, is_released)
;

CREATE TABLE IF NOT EXISTS LANGRAPH4J_CHECKPOINT (
   checkpoint_id VARCHAR2(36) PRIMARY KEY,
   thread_id VARCHAR2(36) NOT NULL,
   node_id VARCHAR(255),
   next_node_id VARCHAR(255),
   state_data CLOB NOT NULL,
   saved_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

   CONSTRAINT LANGRAPH4J_FK_THREAD
       FOREIGN KEY(thread_id)
       REFERENCES LANGRAPH4J_THREAD(thread_id)
       ON DELETE CASCADE
)
