-- sqlCreateTables
CREATE TABLE IF NOT EXISTS LG4JThread (
    thread_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_name VARCHAR2(255) UNIQUE NOT NULL,
    parent_thread_id NUMBER(19),
    is_interrupted NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_interrupted IN (0, 1)),
    message CLOB,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (parent_thread_id) REFERENCES LG4JThread(thread_id)
);

CREATE TABLE IF NOT EXISTS LG4JThreadTag (
    thread_id NUMBER(19) PRIMARY KEY,
    thread_name VARCHAR2(255),
    released_version NUMBER(10),
    parent_thread_id NUMBER(19),
    is_released NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_released IN (0, 1)),
    is_error NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_error IN (0, 1)),
    message CLOB,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS LG4JCheckpoint (
    checkpoint_id VARCHAR2(255) PRIMARY KEY,
    parent_checkpoint_id VARCHAR2(255),
    thread_id NUMBER(19) NOT NULL,
    node_id VARCHAR2(255),
    next_node_id VARCHAR2(255),
    state_data CLOB NOT NULL,
    state_content_type VARCHAR2(255) NOT NULL,
    saved_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL

);

CREATE INDEX IF NOT EXISTS idx_lg4jcheckpoint_thread_id ON LG4JCheckpoint(thread_id);
CREATE INDEX IF NOT EXISTS idx_lg4jcheckpoint_thread_id_saved_at_desc ON LG4JCheckpoint(thread_id, saved_at DESC);
